### ISSUE TITLE
Functionality plugin name

### ISSUE THREAD

**Issue by webelaine** [a8cteam51/build-processes-demo#18]
The word "extra" in the `{site}-functionality-plugin` folder suggests optional or non-core functionality to me, but usually that plugin contains a lot of critical things for the site. What if we simplified the name to just `{site}-functionality` or `{site}-features`?

**Comment by ahegyes** [comment]
Thanks for proposing this @webelaine!

It would be perfectly fine to deviate from that folder's naming on a per-project basis, but we agreed that renaming it to `-features` makes more sense as a default. 

The changes for this have been pushed already, so I'm closing the issue but feel free to re-open it if you want to add something or if you feel like I've missed anything :)
