### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by webelaine** [a8cteam51/build-processes-demo#20]
At least from my team's standpoint, GitHub issues are usually written more like features and user stories. The template included in the demo is a more rigid bug template - how to reproduce, etc. Not a big deal at all, especially if other teams frequently find the bug template useful - it's easy to erase and just write issues however they are needed at the time, just thought I would mention to see if anyone else typically finds themselves selecting all and deleting the template in favor of another approach.

**Comment by fmfernandes** [comment]
Hi @webelaine 👋🏻 

We can definitely add more templates! We could add a template for bug reports and features/task which might cover the scenarios you mentioned. There's some good examples on the [Calypso](https://github.com/Automattic/wp-calypso/issues/new/choose) repo and we can also have a blank template if none works. Could you please share some templates that you've found useful?

Thanks!

**Comment by webelaine** [comment]
Something along the lines of the Calypso Feature Request template is what I was thinking. I'm not thinking of a particular template I've seen, but something like this would be my approach:

#### Feature description
- What will this feature accomplish?
- What would the minimum viable product include?
- What are some nice-to-haves?

#### Integrations
- What plugins does the feature need to integrate with?

#### Next steps
- What should we focus on next? Is more discovery needed, or are there concrete deliverables we can work on?

#### Research
- Links to previous work or other sites that do something similar

**Comment by fmfernandes** [comment]
Thanks @webelaine!

I've added a couple templates on #28.

**Comment by webelaine** [comment]
Thanks, @fmfernandes ! That looks great.
