### ISSUE TITLE
npm-run-all not running all the scripts in parallel

### ISSUE THREAD

**Issue by bernattorras** [a8cteam51/build-processes-demo#24]
#### Description

When using commands line `npm run start`, it is expected that all the commands that start with `start:` are executed in parallel (like `start:blocks`, `start:scripts:theme`, `start:scripts:plugin`, etc), but that doesn't seem to be the case, as it is currently only running the first one and getting stuck there. 

Commands from package.json:
```
"start": "npm-run-all start:* --parallel",
"start:blocks": "wp-scripts start --webpack-src-dir=mu-plugins/$npm_package_name-blocks/src --output-path=mu-plugins/$npm_package_name-blocks/build",
"start:scripts:theme": "wp-scripts start --webpack-src-dir=themes/$npm_package_name/assets/js/src --output-path=themes/$npm_package_name/assets/js/build",
"start:scripts:plugin": "wp-scripts start --webpack-src-dir=mu-plugins/$npm_package_name-extra-functionality/assets/js/src --output-path=mu-plugins/$npm_package_name-extra-functionality/assets/js/build",
"start:styles:theme": "sass --watch themes/$npm_package_name/assets/css/src:themes/$npm_package_name/assets/css/build",
"start:styles:theme-stylesheet": "sass --watch themes/$npm_package_name/assets/scss/style.scss themes/$npm_package_name/style.css",
"start:styles:theme-editor": "sass --watch themes/$npm_package_name/assets/scss/style-editor.scss themes/$npm_package_name/style-editor.css",
"start:styles:plugin": "sass --watch mu-plugins/$npm_package_name-extra-functionality/assets/css/src:mu-plugins/$npm_package_name-extra-functionality/assets/css/build"
```

#### Steps to reproduce
1. Clone the repository locally
2. Run `npm run start`
3. Check if all the `start:xxx:xxx` scripts are executed or if only the first one (`start:blocks` is running)
4. Try to apply some changes to some theme or plugin `scss` or `js` files to see if the build is updated as expected.

#### What I expected

I expected all the `start:*:*` scripts to run in parallel, so apart from building the blocks, all the other files (SCSS, CSS, JS, etc) are processed as well when updated.

#### What happened instead

When running `npm run start` only the first `start:blocks` gets executed, instead of executing the rest of the `start: ` commands in parallel.

#### Browser / OS version
Chrome: Version 108.0.5359.124 (Official Build) (x86_64)
MacOS: 11.5.2

#### Screenshot / Video
![https://d.pr/v/e7V116](https://d.pr/v/e7V116+) 
Full Size: https://d.pr/v/e7V116

**Comment by ahegyes** [comment]
Thanks @bernattorras! The PR you submitted works great in addressing this issue. I'm approving it shortly.
