### ISSUE TITLE
Replace SCSS `@import` with `@use` and `@forward`

### ISSUE THREAD

**Issue by chrisbellboy** [a8cteam51/build-processes-demo#33]
`@import` was deprecated a few years ago (along with node-sass) and will stop working at some point. It's better to use `@use` and `@forward` as they also allow for namespacing and cleaner folder structures.

I've prepared a PR for this in case it helps. If it's a goer, feel free to let me know if it needs any tweaks at all! 🤓

**Comment by tommusrhodus** [comment]
@chrisbellboy closing this out as #34 will be merged, great work 👍
