### ISSUE TITLE
Standardise media breakpoints + mixins

### ISSUE THREAD

**Issue by chrisbellboy** [a8cteam51/build-processes-demo#35]
Practically every project (even FSE) will need to use breakpoints. I'm not sure if this is within the scope of this repo, but could be a good opportunity to standardise it.

I've created another PR on top of #34 to add a base mixin that should cover 95% of theme needs. It's inspired a bit by Bootstrap 5's breakpoints logic 🤓

**Comment by tommusrhodus** [comment]
PR is merged! Thanks @chrisbellboy 👍
