### ISSUE TITLE
Update `/sass/` folder names to `/scss/`

### ISSUE THREAD

**Issue by tommusrhodus** [a8cteam51/build-processes-demo#43]
### Description

SASS and SCSS are different things, we're using SCSS so for completeness, let's update the folder names.

H/T to @chrisbellboy and @ahegyes

**Comment by ahegyes** [comment]
Nope, I changed my mind again. I want to advocate **against** changing the folder name back to `scss` 😅 

Two reasons:

1. This image: 
![image](https://user-images.githubusercontent.com/36231502/223791698-e210d128-1b02-438b-9504-b96e36552435.png)

2. All the A8C themes I've checked name the folder `sass`

**Comment by ahegyes** [comment]
I do want to make a motion to rename the `sass/core` folder to `sass/base` and the `sass/layouts` folder to `sass/layout` though 😅 Thoughts?

**Comment by tommusrhodus** [comment]
@ahegyes I'm happy to use your suggestion of following: https://gist.github.com/AdamMarsden/7b85e8d5bdb5bef969a0

Its very clear and well documented 👍

**Comment by ahegyes** [comment]
Done -- I updated the folder structure and the README.

**Comment by ahegyes** [comment]
Noting here that while fixing linting errors, I noticed that our new breakpoint mixins are failing for what I see as false positives. As a result, I've opened this issue on the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/48992
